server:
  port: 8080

spring:
  datasource:
    username: root
    password: Greeting
    url: jdbc:h2:mem:emp_db
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect:
        hibernate: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        properties: 
          format-sql: true
